# Generated by Django 3.0.5 on 2021-05-18 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_number', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('vat_country', models.CharField(max_length=100)),
                ('vat_id', models.CharField(max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_type', models.CharField(choices=[('PROFORMA', 'Proforma'), ('INTERIM', 'Interim'), ('COLLECTIVE', 'Collective'), ('FINAL', 'Final'), ('RECURRING', 'Recurring')], max_length=12)),
                ('invoice_state', models.CharField(choices=[('ISSUED', 'Issued'), ('DRAFT', 'Draft'), ('PAID', 'Paid')], max_length=10)),
                ('currency', models.CharField(choices=[('RON', 'Romania'), ('RUB', 'Russia'), ('NIO', 'Nicaragua'), ('CAD', 'Canada'), ('USD', 'United States'), ('EUR', 'Spain')], max_length=13)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payparc_invoicing.CustomerModel')),
            ],
            options={
                'verbose_name': 'Invoice',
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItemsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payparc_invoicing.InvoiceModel')),
            ],
            options={
                'verbose_name': 'Invoice item',
                'db_table': 'invoice_item',
            },
        ),
    ]
